yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}


<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">

      <div class="card-header">Войти на сайт</div>

      <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}


        <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}">
          <div class="form-group row">
              <label for="{{ form.username.id_for_label }}" class="col-md-4 col-form-label text-md-right">Имя пользователя</label>
              <div class="col-md-6">
                  {{ form.username|addclass:"form-control" }}
              </div>
          </div>

          <div class="form-group row">
              <label for="{{ form.password.id_for_label }}" class="col-md-4 col-form-label text-md-right">Пароль</label>
              <div class="col-md-6">
                  {{ form.password|addclass:"form-control" }}
              </div>
          </div>

          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}Изменение пароля{% endblock %}

{% block content %}
{% load user_filters %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        
        <div class="card-header">
          Изменить пароль
        </div>

        <div class="card-body">
          <form method="post" action="{% url 'users:password_change' %}">
            {% csrf_token %}

            {% for field in form %} 
            <div class="form-group row my-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
          {% endfor %}


            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>

          </form>
        </div> 
        
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Сброс пароля прошёл успешно{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">

          <div class="card-header">
            Восстановление пароля завершено
          </div>

          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div> 

        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Новый пароль{% endblock %}

{% block content %}
{% load user_filters %}

{% if validlink %}

<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">

        <div class="card-header">
          Введите новый пароль
        </div>

        <div class="card-body">
          <form method="post" action={% url 'users:password_reset_confirm' %}>
            {% csrf_token %}
            
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small 
                       id="{{ field.id_for_label }}-help"
                       class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div> 

      </div>
    </div>
  </div>

{% else %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">

        <div class="card-header">
          Ошибка
        </div>
        
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div>
        
      </div>
    </div>
  </div>

</div>

{% endif %}
{% endblock %}

yatube/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}
  Зарегистрироваться
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">

        <div class="card-header">
          Зарегистрироваться
        </div>

        <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                {% for field in form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }} 
                      {% if field.help_text %}
                        <small 
                           id="{{ field.id_for_label }}-help"
                           class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                  </button>
                </div>
              </form>
        </div>
        
      </div>
    </div>
  </div>
{% endblock %} 